services:
  web:
    build:
      context: .
      target: builder
    container_name: inacanoe-qa-web
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - '5010:8080'
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - redis
      - postgres_db

  redis:
    image: redislabs/redismod
    container_name: inacanoe-qa-redis
    ports:
      - '6379:6379'
    volumes:
      - ./redis_storage:/data

  postgres_db:
    image: "postgres"
    container_name: inacanoe-qa-postgres
    ports:
      - '5432:5432'
      - '8080:8080'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
