services:

  web:
    build:
      context: .
      target: builder
    ports:
     - "5010:80"
    volumes:
     - .:/project
    env_file:
      - .env
    depends_on:
      - redis
      - postgres_db

  redis:
    image: redislabs/redismod
    ports:
      - '6379:6379'
    volumes:
      - ./redis_storage:/data

  postgres_db:
    image: "postgres"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
