services:
  web:
    build:
      context: .
      target: builder
    container_name: inacanoe-prod-web
    ports:
     - "5010:5010"
    volumes:
     - .:/project
     - ./tmp:/tmp
     - ./server-conf/uwsgi.ini:/etc/uwsgi/uwsgi.ini
    env_file:
      - .env
    depends_on:
      - redis
      - postgres_db

  redis:
    image: redislabs/redismod
    container_name: inacanoe-prod-redis
    ports:
      - '6379:6379'
    volumes:
      - ./redis_storage:/data

  postgres_db:
    image: "postgres"
    container_name: inacanoe-prod-postgres_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
